#spass 파일을 읽기 위해 라이브러리 설치
!pip install pyreadstat

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_spss('content/koweps_hpc19_2024_beta1.sav')
row_data = df.copy()
df.tail()
#print(df['h19_g3','h19_g4','p1902_8aq1','h19_eco9'])

,h19_id,h19_ind,h19_sn,h19_merkey,h_new,h_new1,h19_cobf,p19_wsc,p19_wsl,p19_wgc,...,c1907_4aq19,c1907_4aq20,c1907_4aq21,c1907_4aq22,c1907_4aq23,h19_pers_income1,h19_pers_income2,h19_pers_income3,h19_pers_income4,h19_pers_income5
15417,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,12320.0,NaN,NaN,0.0,NaN
15418,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3120.0,NaN,0.0,NaN
15419,12010.0,17.0,1.0,120101701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
15420,12011.0,17.0,1.0,120111701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7200.0,-1800.0,0.0,NaN
15421,12011.0,17.0,1.0,120111701.0,0.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15422 entries, 0 to 15421
Columns: 1046 entries, h19_id to h19_pers_income5
dtypes: float64(1045), object(1)
memory usage: 123.1+ MB

In [26]:
df.columns #데이터프레임에 포함된 모든 컬럼명(변수명) 확인

Index(['h19_id', 'h19_ind', 'h19_sn', 'h19_merkey', 'h_new', 'h_new1',
       'h19_cobf', 'p19_wsc', 'p19_wsl', 'p19_wgc',
       ...
       'c1907_4aq19', 'c1907_4aq20', 'c1907_4aq21', 'c1907_4aq22',
       'c1907_4aq23', 'h19_pers_income1', 'h19_pers_income2',
       'h19_pers_income3', 'h19_pers_income4', 'h19_pers_income5'],
      dtype='object', length=1046)

In [27]:
df.describe()

,h19_id,h19_ind,h19_sn,h19_merkey,h_new,h_new1,h19_cobf,p19_wsc,p19_wsl,p19_wgc,...,c1907_4aq19,c1907_4aq20,c1907_4aq21,c1907_4aq22,c1907_4aq23,h19_pers_income1,h19_pers_income2,h19_pers_income3,h19_pers_income4,h19_pers_income5
count,15422.000000,15422.000000,15422.000000,1.542200e+04,15422.000000,15422.000000,138.000000,9547.000000,9547.000000,9547.000000,...,330.000000,330.000000,330.000000,330.000000,330.000000,2844.000000,4107.000000,1075.000000,15422.000000,896.000000
mean,6101.584555,7.012450,1.005771,6.101655e+07,0.154195,0.226754,2.181159,1.000000,1.000000,5416.635487,...,2.915152,1.909091,1.803030,1.721212,2.921212,4954.102321,1664.679571,4162.537674,4.250940,1306.699777
std,3627.634224,6.766716,0.143259,3.627682e+07,0.361148,0.418746,1.617584,0.667145,0.726814,3613.678770,...,0.722256,0.793731,0.731815,0.676014,0.710220,2940.527076,1661.234908,5478.355826,65.450626,2351.891839
min,2.000000,1.000000,1.000000,2.010100e+04,0.000000,0.000000,1.000000,0.009622,0.000000,52.117115,...,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,-28564.000000,-148.000000,-11990.000000
25%,2969.000000,1.000000,1.000000,2.969010e+07,0.000000,0.000000,1.000000,0.483828,0.446592,2620.719401,...,2.000000,1.000000,1.000000,1.000000,3.000000,3050.000000,300.000000,1422.000000,0.000000,225.750000
50%,5676.500000,5.000000,1.000000,5.676540e+07,0.000000,0.000000,2.000000,0.921310,0.845038,4990.402553,...,3.000000,2.000000,2.000000,2.000000,3.000000,4190.000000,1196.000000,3000.000000,0.000000,532.000000
75%,9541.500000,17.000000,1.000000,9.541570e+07,0.000000,0.000000,2.000000,1.381663,1.394530,7483.966844,...,3.000000,2.000000,2.000000,2.000000,3.000000,6233.000000,2520.000000,5303.500000,0.000000,1362.250000
max,12011.000000,19.000000,9.000000,1.201117e+08,1.000000,1.000000,7.000000,3.640399,2.945577,19718.713804,...,4.000000,4.000000,4.000000,4.000000,4.000000,25168.000000,27144.000000,65000.000000,4000.000000,22000.000000

In [ ]:
print(df[['h19_g3','h19_g4','p1902_8aq1','h19_eco9']])
## 성별 출생년도 월평균임금 직업